//? Redux-Sage
export const GET_DANH_SACH_NGUOI_DUNG_ADMIN = "GET_DANH_SACH_NGUOI_DUNG_ADMIN";
export const GET_THONG_TIN_USER_ADMIN = "GET_THONG_TIN_USER_ADMIN";

export const THEM_NGUOI_DUNG_ADMIN = "THEM_NGUOI_DUNG_ADMIN";
export const XOA_NGUOI_DUNG_ADMIN = "XOA_NGUOI_DUNG_ADMIN";

export const GET_DANH_SACH_KHOA_HOC_ADMIN = "GET_DANH_SACH_KHOA_HOC_ADMIN";
export const XOA_KHOA_HOC_ADMIN = "XOA_KHOA_HOC_ADMIN";
export const GET_DANH_MUC_ADMIN = "GET_DANH_MUC_ADMIN";
export const THEM_KHOA_HOC_ADMIN = "THEM_KHOA_HOC_ADMIN";

//? Redux-Reducer
export const DANH_SACH_NGUOI_DUNG_ADMIN_REDUCER =
  "DANH_SACH_NGUOI_DUNG_ADMIN_REDUCER";
export const THONG_TIN_USER_ADMIN_REDUCER = "THONG_TIN_USER_ADMIN_REDUCER";

export const DANH_SACH_KHOA_HOC_ADMIN_REDUCER =
  "DANH_SACH_KHOA_HOC_ADMIN_REDUCER";
export const GET_DANH_MUC_ADMIN_REDUCER = "GET_DANH_MUC_ADMIN_REDUCER";
