export const LAY_KHOA_HOC_MOI = "LAY_KHOA_HOC_MOI";
export const LAY_DANH_MUC = "LAY_DANH_MUC";
export const LAY_KHOA_HOC_DANH_MUC = "LAY_KHOA_HOC_DANH_MUC";
export const LAY_CHI_TIET_KHOA_HOC = "LAY_CHI_TIET_KHOA_HOC";

export const DANG_KY_USER = "DANG_KY_USER";
export const DANG_NHAP_USER = "DANG_NHAP_USER";
export const LAY_THONG_TIN_USER = "LAY_THONG_TIN_USER";

export const EDIT_THONG_TIN_USER = "EDIT_THONG_TIN_USER";
export const DANG_KY_KHOA_HOC = "DANG_KY_KHOA_HOC";
export const LAY_DS_KHOA_HOC_CHO_DUYET = "LAY_DS_KHOA_HOC_CHO_DUYET";
export const XOA_KHOA_HOC = "XOA_KHOA_HOC";
//Redux-Reducer
export const GET_KHOA_HOC_MOI_REDUCER = "GET_KHOA_HOC_MOI_REDUCER";
export const GET_DANH_MUC_REDUCER = "GET_DANH_MUC_REDUCER";
export const GET_KHOA_HOC_DANH_MUC_REDUCER = "GET_KHOA_HOC_DANH_MUC_REDUCER";
export const GET_CHI_TIET_KHOA_HOC_REDUCER = "GET_CHI_TIET_KHOA_HOC";
export const HUY_GHI_DANH_KHOA_HOC_USER = "HUY_GHI_DANH_KHOA_HOC_USER";

export const GET_KHOA_HOC_DANG_KY = "GET_KHOA_HOC_DANG_KY";

export const GET_USER_LOG_IN = "GET_USER_LOG_IN";
export const GET_THONG_TIN_USER = "GET_THONG_TIN_USER";
